# Generated by Django 5.0.14 on 2026-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('hf', 'HuggingFace'), ('other', 'Other')], db_index=True, max_length=20)),
                ('operation', models.CharField(choices=[('extraction', 'Extraction/Classification'), ('matching', 'Semantic Matching'), ('other', 'Other')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(help_text='Duration in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('tokens_used', models.IntegerField(blank=True, default=0, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tier', 'timestamp'], name='analytics_a_tier_97c96b_idx'), models.Index(fields=['operation', 'success'], name='analytics_a_operati_7edc51_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField(db_index=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('job_processing_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
