# Generated by Django 5.0.14 on 2025-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='match_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(default='keyword', help_text='Source of the match (e.g., gemini, keyword)', max_length=50),
        ),
    ]
