# Generated by Django 5.0.14 on 2026-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='feedback',
            field=models.CharField(choices=[('pending', 'Pending'), ('relevant', 'Relevant'), ('not_relevant', 'Not Relevant')], default='pending', max_length=15),
        ),
    ]
