# Generated by Django 5.0.14 on 2025-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="User's self-description for AI-powered job matching"),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-level (2-5 years)'), ('senior', 'Senior (5+ years)'), ('lead', 'Lead/Principal (8+ years)')], help_text='Experience level for job matching', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Total years of professional experience', null=True),
        ),
    ]
