# Generated by Django 5.0.14 on 2025-12-19 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_experience_level_user_years_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Desired job roles (e.g., 'Backend Developer', 'DevOps Engineer')", size=None),
        ),
    ]
