# Generated by Django 5.0.14 on 2025-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_category',
            field=models.CharField(blank=True, choices=[('software', 'Software Development'), ('marketing', 'Marketing'), ('design', 'Design'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('customer_service', 'Customer Service'), ('management', 'Management'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('all', 'Any / All')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('all', 'Any / All')], default='all', max_length=20),
        ),
    ]
