# Generated by Django 5.0.14 on 2025-12-16 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Channel username (e.g. @jobs)', max_length=255, unique=True)),
                ('channel_id', models.BigIntegerField(blank=True, help_text='Telegram Channel ID', null=True, unique=True)),
                ('last_scraped_id', models.IntegerField(default=0, help_text='ID of the last message scraped')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
