# Generated by Django 5.0.14 on 2025-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_username',
            field=models.CharField(default=1, help_text='Telegram username WITHOUT @ (e.g. pythonjobs)', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram Channel ID (Auto-populated if possible)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text='Human readable name (e.g. Python Jobs)', max_length=255),
        ),
    ]
