# Generated by Django 5.0.14 on 2026-01-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_remove_channel_added_by_channel_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.CharField(choices=[('software', 'Software Development'), ('marketing', 'Marketing'), ('design', 'Design'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('customer_service', 'Customer Service'), ('management', 'Management'), ('other', 'Other'), ('general', 'General / All')], default='general', help_text='Category for filtering featured channels', max_length=50),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="If True, appears in the 'Featured Channels' list during onboarding"),
        ),
    ]
