# Generated by Django 5.0.14 on 2025-12-16 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(help_text='Telegram Message ID in the channel')),
                ('raw_text', models.TextField(help_text='Original raw text from Telegram')),
                ('clean_text', models.TextField(blank=True, help_text='Text cleaned for matching')),
                ('source_link', models.URLField(help_text='Direct link to the post', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channels.channel')),
            ],
            options={
                'indexes': [models.Index(fields=['is_processed', 'created_at'], name='jobs_jobpos_is_proc_3f1051_idx')],
                'unique_together': {('channel', 'message_id')},
            },
        ),
    ]
