# Generated by Django 5.0.14 on 2025-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(blank=True, choices=[('software', 'Software Development'), ('marketing', 'Marketing'), ('design', 'Design'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('customer_service', 'Customer Service'), ('management', 'Management'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20, null=True),
        ),
    ]
