# Generated by Django 5.0.14 on 2025-12-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_category_jobpost_job_type_jobpost_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_job',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Whether this post is classified as a job posting (vs announcement/spam)'
            ),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='classification_confidence',
            field=models.IntegerField(
                blank=True,
                help_text='AI confidence score (0-100) for job classification',
                null=True
            ),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_job', 'created_at'], name='jobs_jobpos_is_job_idx'),
        ),
    ]
