# Generated by Django 5.0.14 on 2025-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_job_classification_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobpost',
            new_name='jobs_jobpos_is_job_f05ba0_idx',
            old_name='jobs_jobpos_is_job_idx',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='needs_metadata_extraction',
            field=models.BooleanField(default=False, help_text='True if AI failed during ingestion and requires retry'),
        ),
    ]
