# Generated by Django 5.0.14 on 2026-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_jobs_jobpos_is_job_idx_jobs_jobpos_is_job_f05ba0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='ai_tier_classification',
            field=models.CharField(blank=True, choices=[('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('huggingface', 'HuggingFace')], help_text='Which AI tier was used for classification/extraction', max_length=20, null=True),
        ),
    ]
